import type { Decimal } from "@prisma/client/runtime/library";
import { offlineGraphql } from "./shopify-graphql.server";

export type OrderLine = {
  shopifyVariantId: string;
  quantity: number;
  title: string;
  price: Decimal;
};

type DraftOrderCreateResult = {
  draftOrderCreate: {
    draftOrder: { id: string } | null;
    userErrors: Array<{ field: string[] | null; message: string }>;
  };
};

type DraftOrderCompleteResult = {
  draftOrderComplete: {
    draftOrder: { id: string; order: { id: string; displayFinancialStatus: string | null } | null } | null;
    userErrors: Array<{ field: string[] | null; message: string }>;
  };
};

export async function createInvoiceOrder(params: {
  shop: string;
  customerId: string;
  subscriptionId: string;
  lines: OrderLine[];
}) {
  const paymentTermsTemplateId = process.env.SHOPIFY_PAYMENT_TERMS_TEMPLATE_ID;

  const input: Record<string, unknown> = {
    purchasingEntity: { customerId: params.customerId },
    lineItems: params.lines.map((line) => ({
      variantId: line.shopifyVariantId,
      quantity: line.quantity,
    })),
    tags: ["Subscription Order", `subscription:${params.subscriptionId}`],
    note: `Invoice subscription order generated by app for subscription ${params.subscriptionId}`,
    customAttributes: [
      { key: "subscription_id", value: params.subscriptionId },
      { key: "generated_by", value: "invoice-subscription-app" },
    ],
    visibleToCustomer: true,
  };

  if (paymentTermsTemplateId) {
    input.paymentTerms = { paymentTermsTemplateId };
  }

  const create = await offlineGraphql<DraftOrderCreateResult>(
    params.shop,
    `#graphql
      mutation CreateSubscriptionDraft($input: DraftOrderInput!) {
        draftOrderCreate(input: $input) {
          draftOrder { id }
          userErrors { field message }
        }
      }
    `,
    { input },
  );

  assertNoUserErrors(create.draftOrderCreate.userErrors);
  const draftOrderId = create.draftOrderCreate.draftOrder?.id;
  if (!draftOrderId) throw new Error("Shopify did not return a draft order ID");

  const complete = await offlineGraphql<DraftOrderCompleteResult>(
    params.shop,
    `#graphql
      mutation CompleteSubscriptionDraft($id: ID!) {
        draftOrderComplete(id: $id, paymentPending: true) {
          draftOrder {
            id
            order {
              id
              displayFinancialStatus
            }
          }
          userErrors { field message }
        }
      }
    `,
    { id: draftOrderId },
  );

  assertNoUserErrors(complete.draftOrderComplete.userErrors);
  const order = complete.draftOrderComplete.draftOrder?.order;
  if (!order?.id) throw new Error("Shopify did not create an order from the draft");

  return {
    shopifyOrderId: order.id,
    invoiceStatus: order.displayFinancialStatus ?? "PENDING",
  };
}

function assertNoUserErrors(errors: Array<{ field: string[] | null; message: string }>) {
  if (errors.length) {
    throw new Error(errors.map((error) => `${error.field?.join(".") ?? "input"}: ${error.message}`).join("; "));
  }
}
