name = "Invoice Subscription Ordering"
client_id = "8104c62409396423a47149e941efc553"
application_url = "https://portal.codesdesk.com"
embedded = true

[access_scopes]
scopes = "read_customers,write_customers,read_products,read_orders,write_orders,read_draft_orders,write_draft_orders,read_payment_terms,write_payment_terms"

[auth]
redirect_urls = [
  "https://portal.codesdesk.com/auth/callback",
  "https://portal.codesdesk.com/auth/shopify/callback",
  "https://portal.codesdesk.com/api/auth/callback"
]

[webhooks]
api_version = "2026-07"

[app_proxy]
url = "https://portal.codesdesk.com"
subpath = "subscription-portal"
prefix = "apps"
